name: workflow for jenkins trigger

on:
  push:
    branches:
    - stg
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: trigger Job
      uses: jabbukka/jenkins-trigger@main
      with:
        url: "https://jenkins.quinnox.info"
        job_name: "stg-githubactions-job"
        user_name: "admin"
        api_token: ${{ secrets.JEN_TOKEN }}
