name: workflow for jenkins trigger

on:
  push:
    branches:
    - stg
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: trigger Job
      uses: GoldenspearLLC/build-jenkins-job@master
      with:
        jenkins-url: "https://jenkins.quinnox.info"
        jenkins-token: ${{ secrets.JEN_TOKEN }}
        user: "admin"
        job-path: "/jenkins/view/Staging-Service-Deployments/stg-githubactions-job"
