name: workflow for jenkins trigger

on:
  push:
    branches:
    - stg
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: curl
      uses: wei/curl@v1
      with:
        args: -X POST https://httpbin.org/post
    - name: trigger Job
      uses: mickeygoussetorg/trigger-jenkins-job@v1
      with:
        jenkins-server:  "https://jenkins.quinnox.info"
        jenkins-job: "stg-githubactions-job"
        jenkins-username: "admin" 
        jenkins-pat: ${{ secrets.JENKINS_PAT }} 
        
