name: workflow for jenkins trigger

on:
  push:
    branches:
    - stg
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: trigger single Job
      uses: mickeygoussetorg/trigger-jenkins-job@v1
      with:
        url: "https://jenkins.quinnox.info"
        user: "admin"
        token: ${{ secrets.JEN_TOKEN }}
        job: "stg-githubactions-job"
