name: workflow for jenkins trigger

on:
  push:
    branches:
    - stg
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: trigger Job
      uses: appleboy/jenkins-action@master
      with:
        url: "https://jenkins.quinnox.info"
        user: "admin"
        token: ${{ secrets.JEN_TOKEN }}
        job: "stg-githubactions-job"
