name: workflow for jenkins trigger

on:
  push:
    branches:
    - stg
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: trigger Job
      uses: mickeygoussetorg/trigger-jenkins-job@v1
      with:
        jenkins-server:  "https://jenkins.quinnox.info"
        jenkins-job: "stg-githubactions-job"
        jenkins-username: "admin" 
        jenkins-pat: ${{ secrets.JENKINS_PAT }}
        poll-time: 10 # how often to poll the jenkins server for results
        timeout-value: 600 # How long to poll before timing out the action
        verbose: true 
        
