name: workflow for jenkins trigger

on:
  push:
    branches:
    - stg
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: get crumb
      run: curl -X POST -u admin:kG8zt8dmP666G5Ca https://jenkins.quinnox.info/jenkins/view/Staging-Service-Deployments/job/stg-githubactions-job/build?token=1234567
  
