name: workflow for jenkins trigger

on:
  push:
    branches:
    - stg
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: get crumb
      run: curl -s -u "admin:kG8zt8dmP666G5Ca" https://jenkins.quinnox.info'/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)'
  
