name: workflow for PR

on:
  push:
    branches:
    - dev
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checking out
      uses: actions/checkout@v2
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@v1.2.0
      with:
        host: ${{ secrets.SONARQUBE_HOST }}
        login: ${{ secrets.SONARQUBE_TOKEN }}
        projectBaseDir: "src/"
        projectKey: "java-sonar-runner-simple"
