name: workflow for PR

on:
  push:
    branches:
    - dev
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/chckout@v4
      with:
          repo-token: ${{ secrets.GIT_TOKEN }}
