name: workflow for PR

on:
  pull_request:
    branches:
    - stg
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: AveryCameronUofR/add-reviewer-gh-action@1.0.3
        with:
          token: ${{ secrets.GIT_TOKEN }}
          reviewers: mummina naidu
